# Generated by Django 5.2.2 on 2025-07-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0002_rename_event_year_events_event_month_events_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='author_img_url',
            field=models.URLField(default='http://www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='author_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='course_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='sub_title',
            field=models.CharField(default='none', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='img_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='img_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='services',
            name='img_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='img_url',
            field=models.URLField(max_length=500),
        ),
    ]
