# Generated by Django 5.2.2 on 2025-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0003_courses_author_img_url_courses_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='author_bio',
            field=models.TextField(default='Dedicated professional with extensive experience in academic instruction. Committed to delivering high-quality education and fostering student success through innovative teaching methodologies.'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='author_img_url',
            field=models.URLField(default='https://via.placeholder.com/150x150?text=Author', null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='img_url',
            field=models.URLField(default='https://via.placeholder.com/300x200?text=Course+Image', null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='sub_title',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
