# Generated by Django 5.2.2 on 2025-07-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0004_courses_author_bio_alter_courses_author_img_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('enroll_class', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=11)),
                ('e_mail', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField()),
                ('additional_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_fees', models.IntegerField(default=0)),
                ('lower_secondary', models.IntegerField(default=0)),
                ('secondary', models.IntegerField(default=0)),
            ],
        ),
    ]
