# Generated by Django 5.2.2 on 2025-07-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0007_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollrequest',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
