# Generated by Django 5.2.2 on 2025-07-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0009_achievements_history_missions_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
