# Generated by Django 5.2.2 on 2025-07-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0010_alter_history_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='emoji',
            field=models.CharField(max_length=100),
        ),
    ]
