# Generated by Django 5.2.2 on 2025-07-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0011_alter_missions_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
    ]
