# Generated by Django 5.2.2 on 2025-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0014_alter_address_options_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ClassName',
                'verbose_name_plural': 'ClassName',
                'ordering': ['name'],
            },
        ),
    ]
